pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.m2 
    volumes:
      - /tmp/cache/.m2
  build: # step name
    image: maven:3-jdk-7	# use docker image
    commands:
    - mvn clean install

  rebuild-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /drone/.m2 
    volumes:
      - /tmp/cache/.m2

  dingtalk:
    image: lddsb/drone-dingtalk-message
    settings:
      token: 
        from_secret: dingding
      type: markdown
    when:
      status: [failure, success]
      brach: [staging]

branches:
  include: [ master, feature/* ]