kind: pipeline
name: pipeline-example-maven

steps:
- name: build
  image: maven:3-jdk-7
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - mvn clean install

- name: 构建镜像  
  image: plugins/docker
  environment:
      - DOCKER_LAUNCH_DEBUG=true
  settings:
    repo: registry-vpc.cn-shanghai.aliyuncs.com/keking/pipeline-example-maven
    auto_tag: true
    username: 
      from_secret: docker_user
    password: 
      from_secret: docker_pass

- name: dingtalk
  image: lddsb/drone-dingtalk-message
  settings:
    token: 
      from_secret: dingding
    type: markdown
  when:
    status: [failure, success]
    brach: [master]

volumes:
- name: cache
  host:
    path: /tmp/cache/.m2

trigger:
  branch:
  - master