pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /root/.m2
    volumes:
      - /tmp/cache/.m2
  build: # step name
    image: maven:3-jdk-7	# use docker image
    commands:
    - mvn clean install

  rebuild-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - /root/.m2
    volumes:
      - /tmp/cache/.m2

  dingtalk:
    image: lddsb/drone-dingtalk-message
    settings:
      token: 
        from_secret: df1daade4b0ad2ec02bef45ac30003da95d52ebf2aa204294730cb86c365c6dd
      type: markdown
    when:
      status: [failure, success]
      brach: [staging]

branches:
  include: [ master, feature/* ]