pipeline:
  build: # step name
    image: maven:3-jdk-7	# use docker image
    commands:
    - mvn clean install

  dingtalk:
    image: xtony77/drone-dingtalk
    secrets: 
      - source: DINGTALK_HOOK
        target: plugin_webhook
    when:
      status: [failure, success]
      brach: [staging]

branches:
  include: [ master, feature/* ]