kind: pipeline
name: default

steps:
- name: build
  image: maven:3-jdk-7
  environment: 
    - M2_HOME=/drone/.m2 
    - MAVEN_HOME=/drone/.m2 
  volumes:
  - name: cache
    path: /drone/.m2 
    commands:
    - mvn clean install

volumes:
- name: cache
  host:
    path: /tmp/cache/.m2

- name: dingtalk
  image: lddsb/drone-dingtalk-message
  settings:
    token: 
      from_secret: dingding
    type: markdown
  when:
    status: [failure, success]
    brach: [master]

branches:
  include: [ master, feature/* ]