kind: pipeline
name: pipeline-example-maven

steps:
- name: Maven编译
  image: maven:3-jdk-7
  volumes:
  - name: cache
    path: /root/.m2
  commands:
    - mvn clean install

- name: 构建镜像  
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_user
    password: 
      from_secret: docker_pass
    repo: registry-vpc.cn-shanghai.aliyuncs.com/keking/pipeline-example-maven
    registry: registry-vpc.cn-shanghai.aliyuncs.com
    tags: ${DRONE_TAG=latest}

- name: Kubernetes 部署
  image: guoxudongdocker/kubectl:v1.14.1  # 这个镜像自己去打即可
  environment:
    KUBECONFIG:
      from_secret: kubeconfig
  commands:
    - cat deployment.yaml
    - ls   
    - ${KUBECONFIG} > /root/.kube/config # k8s 的kubeconfig文件，可以有多个，部署到哪个集群就拷贝哪个kubeconfig文件
    - kubectl get node
    - kubectl apply -f deployment.yaml 

- name: 钉钉通知
  image: lddsb/drone-dingtalk-message 
  settings:
    token: 
      from_secret: dingding
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
  when:
    status: [failure, success]
    brach: [master]

volumes:
- name: cache
  host:
    path: /tmp/cache/.m2

trigger:
  branch:
  - master