stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3.6.1-jdk-8-alpine
      shellScript: |-
        mvn clean install
    envFrom:
    - sourceName: registry-pass
      sourceKey: username
      targetKey: username
    - sourceName: registry-pass
      sourceKey: password
      targetKey: password
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - master
notification: {}
