stages:
- name: Build
  steps:
  - runScriptConfig:
      image: registry-vpc.cn-shanghai.aliyuncs.com/keking/maven:3.6.1-jdk-8-alpine
      shellScript: mvn clean install
    envFrom:
    - sourceName: registry-pass
      sourceKey: username
      targetKey: username
    - sourceName: registry-pass
      sourceKey: password
      targetKey: password
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry-vpc.cn-shanghai.aliyuncs.com/keking/example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry-vpc.cn-shanghai.aliyuncs.com/keking/
    env:
      DOCKER_HOST: tcp://dind.devops-plat:2375
      PLUGIN_DAEMON_OFF: true
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - master
notification: {}
