stages:
- name: Build
  steps:
  - runScriptConfig:
      image: registry-vpc.cn-shanghai.aliyuncs.com/keking/maven:3.6.1-jdk-8-alpine
      shellScript: |-
        git clone http://git.keking.cn/tangshd/kk-deploy-configure.git
        mvn clean install
    envFrom:
    - {}
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
branch:
  include:
  - master
notification: {}
